[phases.setup]
nixPkgs = [
    "python3",
    "gcc",
    "glib",
    "gdk-pixbuf",
    "cairo",
    "pango",
    "harfbuzz",
    "fontconfig",
    "libffi",
    "zlib",
    "libjpeg",
    "openjpeg"
]